FEATURES_REQUIRED += periph_gpio
FEATURES_REQUIRED += periph_gpio_irq
FEATURES_REQUIRED += periph_uart
FEATURES_REQUIRED += periph_cpuid
FEATURES_REQUIRED += periph_pwm

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif
